### PR TITLE
update zig: build_examples: replace exec to run

### PR DESCRIPTION
**Pull request by wrongnull**
This function has been renamed in https://github.com/ziglang/zig/pull/17623

### CODE REVIEW

**Comment by JanBeelte** [comment]
What is preventing this from getting merged?
I tried to get started with mach today and instantly hit this error while trying to compile the first examples.

**Comment by wrongnull** [comment]
> What is preventing this from getting merged? I tried to get started with mach today and instantly hit this error while trying to compile the first examples.

I think it's because you are using a higher than supported [version](https://machengine.org/about/zig-version/).
Unfortunately this package does not support the latest compiler versions

**Comment by JanBeelte** [comment]
> I think it's because you are using a higher than supported [version](https://machengine.org/about/zig-version/). Unfortunately this package does not support the latest compiler versions

Thanks for the input, I am using the version from the AUR (0.12.0-dev.1849+bb0f7d55e)
Supported version is: 0.12.0-dev.1092+68ed78775

It is very hard for me to see why such a minor revision change completely breaks it. Looks like I need something like zig version manager (ZVM).

**Comment by emidoots** [comment]
Sorry for the delay @wrongnull @JanBeelte - as an FYI we are moving to nominated Zig versions: https://devlog.hexops.com/2024/announcing-nominated-zig/

This will help make it more clear when PRs like this will be merged, and also make it more clear which version of Zig all Mach libraries are compatible with. Hope that makes sense!

**Comment by emidoots** [comment]
Will merge this as part of #71

**Comment by JanBeelte** [comment]
> Sorry for the delay @wrongnull @JanBeelte - as an FYI we are moving to nominated Zig versions: https://devlog.hexops.com/2024/announcing-nominated-zig/
> 
> This will help make it more clear when PRs like this will be merged, and also make it more clear which version of Zig all Mach libraries are compatible with. Hope that makes sense!

Very much appreciated! Thanks for getting back to me and keep up the great work!

Best,
jan

**Pull request closed without merging**
